version: "3"

services:
  namenode:
    image: doguin/hadoop-namenode:3.1.3
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 50070:50070

  datanode:
    image: doguin/hadoop-datanode:3.1.3
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
      - 50075:50075

  resourcemanager:
    image: doguin/hadoop-resourcemanager:3.1.3
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088

  nodemanager1:
    image: doguin/hadoop-nodemanager:3.1.3
    container_name: nodemanager
    volumes:
      - hadoop_nodemanager:/hadoop/yarn/local
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042

  historyserver:
    image: doguin/hadoop-historyserver:3.1.3
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
  
  zoo:
    image: zookeeper:3.4.14
    container_name: zoo
    hostname: zoo
    restart: always
    volumes:
      - zoo_data_dir:/data
      - zoo_log_dir:/logs
      - zoo_data_log_dir:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181

  hbase-master:
    image: doguin/hbase-hmaster:2.2.5
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 zoo:2181"
    ports:
      - 16010:16010

  hbase-region:
    image: doguin/hbase-hregionserver:2.2.5
    container_name: hbase-regionserver
    hostname: hbase-region
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 zoo:2181 hbase_master:16000"
    ports:
      - 16030:16030

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hadoop_nodemanager:
  zoo_data_dir:
  zoo_log_dir:
  zoo_data_log_dir:
